empleo_desarrolladores/urls.py
from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('empleo_desarrolladores.views',
    url(r'^offer/(?P<slug_offer>[-\w]+)/$', 'offerDetailsView', name="offer_details_view"),
    url(r'^offer/application/(?P<offer_applicant_token>.*)$', 'successfulApplicationView', name="successful_applicant_view"),
    url(r'^positions/list$', 'positionsListView', name="position_list_view"),
    url(r'^positions/details/(?P<slug_offer>[-\w]+)/$', 'positionDetailsView', name="position_detail_view"),
    url(r'^positions/dashboard/(?P<slug_offer>[-\w]+)/$', 'positionDashBoardView', name="position_dashboard_view"),
    url(r'^positions/create/$', 'createPositionView', name='create_position_view'),
    url(r'^positions/preview/(?P<slug_offer>[-\w]+)$', 'positionPreviewView', name='position_preview_view'),
    url(r'^positions/terminate/(?P<slug_offer>[-\w]+)/$', 'terminatePositionView', name='terminate_position_view'),
     url(r'^positions/renew/(?P<slug_offer>[-\w]+)$', 'positionRenew', name='position_renew_view'),
    url(r'^positions/old/$', 'oldPositionsListView', name='old_positions_list_view'),
    url(r'edit_profile/$', 'userProfileEditView',name="edit_profile"),
    url(r'^positions/clarifications/(?P<slug_offer>[-\w]+)$', 'positionClarificationsView', name='position_clarifications_view'),
    url(r'plans_and_pricing/$', 'plansAndPricingView',name="plans_and_pricing"),
    url(r'^company/complete$', 'completeCompanyInfoView',name="complete_company"),
    url(r'^company/details$', 'companyDetailView',name="company_detail"),
    url(r'^purchase/success/(?P<slug_offer>[-\w]+)$', 'purchaseSuccessView',name="purchase_success_view"),
    url(r'^purchase/fail/(?P<slug_offer>[-\w]+)$', 'purchaseFailView',name="purchase_fail_view"),
    url(r'^applicants/resumes/(?P<token>.*)$', 'resumeDownloadView', name="resume_download_view"),
    url(r'^about/$','aboutUsView'),
)

reclutamiento/urls.py
from django.conf.urls.defaults import patterns, include, url
from empleo_desarrolladores.views import  UserProfileEditView, UserProfileDetailView
from empleo_desarrolladores.views import CompanyList, CompanyCreate, CompanyUpdate, CompanyDelete, CompanyUpdate
from empleo_desarrolladores.views import Home
from django.contrib.auth.decorators import login_required as auth
from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^',include('empleo_desarrolladores.urls')),
    url(r'^$', Home.as_view(), name='home'),
    url(r'^company/list$', CompanyList.as_view(), name='company_list'),
    url(r'^company/add/$', CompanyCreate.as_view(), name='company_add'),
    url(r'company/(?P<pk>\d+)/$', CompanyUpdate.as_view(), name='company_update'),
    url(r'company/(?P<pk>\d+)/delete/$', CompanyDelete.as_view(), name='company_delete'),
    url(r"^login/$", "django.contrib.auth.views.login",{"template_name": "registration/login.html"}, name="login"),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),
    url(r"^accounts/", include("registration.backends.default.urls")),
    url(r"edit_profile/$", auth(UserProfileEditView.as_view()),name="edit_profile"),
    # url(r'^$', 'Reclutamiento.views.home', name='home'),
    # url(r'^Reclutamiento/', include('Reclutamiento.foo.urls')),
    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
)

recruiting/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()


urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^',include('empleo_desarrolladores.urls')),
    url(r'^',include('search.urls')),
    # Registration Urls
    url(r"^login/$", "django.contrib.auth.views.login",{"template_name": "registration/login.html"}, name="login"),
    url(r'^logout/$', 'django.contrib.auth.views.logout', {'next_page': '/'}, name='logout'),
    url(r'^accounts/', include("registration.urls")),
    
)

search/urls.py
from django.conf.urls.defaults import *
from haystack.query import SearchQuerySet
from django.conf.urls.defaults import *
from haystack.forms import FacetedSearchForm
from .views import HomeSearchView

# sqs = SearchQuerySet().facet('location')

# urlpatterns = patterns('haystack.views',
#     url(r'^$', HomeSearchView(form_class=FacetedSearchForm ,searchqueryset=sqs, template='search/home.html'), name='home'),
# )

urlpatterns = patterns('search.views',
    url(r'^$', 'homeSearch', name='home'),
)

empleo_desarrolladores/models.py
#!/usr/bin/env python
# encoding: utf-8
from django.db import models
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
from django.utils import timezone
from django.template import defaultfilters
from datetime import datetime, timedelta

class Company(models.Model):

    def url(self, filename):
        path = "media_data/company_image/%s/%s" % (self.name, str(filename))
        return path

    nit = models.CharField(max_length=30, blank=True, null=True, unique=True)
    name = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    website = models.CharField(max_length=100, blank=True, null=True)
    email = models.EmailField(max_length=100)
    phone = models.CharField(max_length=40)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name='Compañia'


class Applicant(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)
    mail = models.EmailField(unique=True)

    def __unicode__(self):
        return self.mail

    def full_name(self):
        return ('%s %s' % (self.first_name, self.last_name)).strip()


class Offer(models.Model):

    job_title = models.CharField(max_length=100)
    location = models.CharField(max_length=100, null=True, default='Bogota')
    TYPE_OF_CONTRACT = (
        ('FT', 'Tiempo Completo'),
        ('PT', 'Medio Tiempo'),
        ('FL', 'Freelance'),
        ('OT', 'Otro'),
    )
    type_contract = models.CharField(max_length=2, choices=TYPE_OF_CONTRACT, default='FT')
    SALARY_CHOICES = (
        (0, 'Negociable'),
        (10, '550.000 - 1.000.000'),
        (15, '1.000.000 - 1.500.000'),
        (20, '1.500.000 - 2.000.000'),
        (25, '2.000.000 - 2.500.000'),
        (30, '2.500.000 - 3.000.000'),
        (35, '3.000.000 - 3.500.000'),
        (40, '3.500.000 - 4.000.000'),
        (45, '4.000.000 - 4.500.000'),
        (50, '4.500.000 - 5.000.000'),
        (55, '5.000.000 - Más'),
    )

    STATE_CHOICES = ((0, 'draft'), (1, 'finished'), (2, 'published'))
    state = models.IntegerField(choices=STATE_CHOICES, default=0)
    applicants = models.ManyToManyField(Applicant, through="OfferApplicant")
    salary = models.IntegerField(max_length=2, choices=SALARY_CHOICES, default=0)
    offer_valid_time = models.DateTimeField()
    skills = TaggableManager()
    job_description = models.TextField(null=False)
    company = models.ForeignKey(Company, null=True)
    slug = models.SlugField(max_length=250, unique=True)
    clarification = models.TextField(null=True, blank=True)
    highlighted = models.BooleanField(default=False)
    ten_days_left_message = models.BooleanField(default=False)

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = defaultfilters.slugify(self.company.name+'-'+self.job_title)
        super(Offer, self).save(*args, **kwargs)

    def days_remaining(self):
        now = timezone.make_aware(datetime.now(), timezone.get_default_timezone())
        days_remaining = self.offer_valid_time - now
        return days_remaining.days

    def ten_days_left(self):
        return self.days_remaining() <= 10

    def get_salary(self):
        for i in self.SALARY_CHOICES:
            if self.salary == i[0]:
                return i[1]

    def set_state(self, state):
        for i in self.STATE_CHOICES:
            if state == i[1]:
                self.state  = i[0]

    def is_published(self):
        return True if self.state==2 else False

    def is_draft(self):
        return True if self.state==0 else False

    def is_finished(self):
        return True if self.state==1 else False

    def __unicode__(self):
        return self.job_title

    def valid_time(self):
        return self.offer_valid_time >= timezone.now() 

    def get_skills(self):
        return ' '.join([x.name for x in self.skills.all()])

class UserProfile(models.Model):
    user = models.OneToOneField(User, unique=True)
    company = models.ForeignKey(Company, null=True, blank=True)

    def __unicode__(self):
        return "%s's profile" % self.user


class OfferApplicant(models.Model):
   
    def url(self, filename):
        path = "multimedia_data/resumes/%s/%s" % (self.token, filename)
        return path
    
    offer = models.ForeignKey(Offer)
    applicant = models.ForeignKey(Applicant)
    observation = models.TextField(blank=True)
    state = models.BooleanField()
    token = models.TextField(unique=True)
    resume = models.FileField(upload_to=url)

    def __unicode__(self):
        return "Offer: " + self.offer.job_title + " Applicant: " + self.applicant.mail

def create_profile(sender, instance, created, **kwargs):
    if created:
        profile, created = UserProfile.objects.get_or_create(user=instance)

from django.db.models.signals import post_save
post_save.connect(create_profile, sender=User)

empleo_desarrolladores/forms.py
#!/usr/bin/env python
# encoding: utf-8
from django import forms
from models import Offer, Company
from taggit.forms import *

class ApplicantForm(forms.Form):
    mail = forms.EmailField(label='Email', widget=forms.TextInput({}))
    first_name = forms.CharField(label='Nombre', widget=forms.TextInput())
    last_name = forms.CharField(label='Apellido', widget=forms.TextInput())
    resume = forms.FileField(label='Hoja de vida')
    observation = forms.CharField(label='Observación', widget=forms.Textarea({'placeholder':'Ingresa alguna observación que tengas con respecto a la oferta o a tus habilidades'}), required=False)


class CreateOfferForm(forms.Form):
    job_title = forms.CharField(label='Título',widget=forms.TextInput())
    job_description = forms.CharField(label='Descripción',widget=forms.Textarea())
    skills = TagField(label='Conocimientos', help_text='Separe los conocimientos que debe tener el desarrollador con comas', widget=forms.TextInput({'placeholder':'Python,Django,SQL'}))
    location = forms.CharField(label='Ciudad', widget=forms.TextInput({'placeholder':'Bogotá'}))
    type_contract = forms.ChoiceField(label='Tipo de contrato', choices=Offer.TYPE_OF_CONTRACT)
    salary = forms.ChoiceField(label='Salario', choices=Offer.SALARY_CHOICES)

class CreateOfferFormLoader():

    def load_initial_data(self, offer):
        s = [skill.name for skill in offer.skills.all()]

        return CreateOfferForm(initial={
            'job_title': offer.job_title,
            'location': offer.location,
            'type_contract': offer.type_contract,
            'salary': offer.salary,
            'offer_valid_time': offer.offer_valid_time,
            'skills': ','.join(s),
            'job_description': offer.job_description,
        })

class CompanyForm(forms.ModelForm):
    nit = forms.RegexField(max_length=30, regex=r'(^[0-9]{5,12}-[0-9]$)', error_message = ('El formato de NIT no es valido, debe ser por Ej.: 123456789-1' ), help_text='Esta información no sera compartida con terceros',required=False)
    name = forms.CharField(label='Nombre', widget=forms.TextInput())
    location = forms.CharField(label='Ciudad',widget=forms.TextInput({'placeholder':'Bogotá', 'id':'company-location'}))
    website = forms.CharField(label='Sitio Web', required=False, widget=forms.TextInput())
    email = forms.EmailField(label='Email', widget=forms.TextInput())
    phone = forms.RegexField(max_length=30, label='Teléfono', required=False, widget=forms.TextInput(), help_text="Código de area + N°. Ej.: (57) 765-4321", error_message = ('El teléfono no es valido'), regex=r'(\d{3}[-\.\s]\d{3}[-\.\s]\d{4}|\(\d{3}\)\s*\d{3}[-\.\s]\d{4}|\d{3}[-\.\s]\d{4})' )
    
    class Meta:
        model = Company

class CompanyFormLoader():
    def load_initial_data(self, company):
        return CompanyForm(initial={
            'nit':company.nit,
            'name':company.name,
            'location':company.location,
            'website':company.website,
            'email':company.email,
            'phone':company.phone,
        })
    
class UserEditForm(forms.Form):
    first_name = forms.CharField(required=False, label='Nombre',widget=forms.TextInput())
    last_name = forms.CharField(required=False, label='Apellidos', widget=forms.TextInput())
    email = forms.EmailField(label='Email', widget=forms.TextInput())

class UserEditFormLoader():
    def load_initial_data(self, user):
        return UserEditForm(initial={
            'first_name':user.first_name,
            'last_name':user.last_name,
            'email':user.email,
        })

class ClarificationForm(forms.Form):
    aclaration = forms.CharField(label='Aclaración', widget=forms.Textarea())

empleo_desarrolladores/templates/company_delete.html
{{ object }}
<form action="." method="post">{% csrf_token %}
    <input type="submit" value="Delete" />
</form>

empleo_desarrolladores/templates/offer_create.html
{% extends 'base.html' %}
{% block content %}
<h1> FORM FOR CREATING JOB OFFERS </h1>
<form class="form-horizontal" action="." method="POST">
    {% for field in form %}
    <div class="control-group {% if field.errors %}error{% endif %}" >
        <label class="control-label">
        {{ field.label }}</label>
        <div class="controls">
            {{ field }}
            <span class="help-inline">{{ field.errors }}</span>
        </div>
    </div>
    {% endfor %}
    {% csrf_token %}
      <div class="control-group">
        <div class="controls">
            <button type="submit" class="btn btn-success btn-large">Guardar</button>
            <a href="{% url 'offer_list' %}" class="btn btn-primary">Cancelar</a>
        </div>
    </div>
</form>
{% endblock %}

empleo_desarrolladores/templates/offer_detail.html
{% extends 'base.html' %}
{% block content  %}
    <div class="bordered2">
        <div class="row-fluid">
            <div class="span11">
                <h1>{{ offer.job_title }}</h1>
            </div>
        </div>
        
        <div class="row-fluid">
            <div class="span6">
                 <h3>{{ offer.offer_company_that_publishes }}</h3>
            </div>
            <div class="span6">
                <p class="pull-right">
                    <strong>Salary:</strong> 
                    {% if offer.salary == 0%}
                        Negotiable
                    {% elif offer.salary == 10 %}
                        550.000 - 1.000.000
                    {% elif offer.salary == 15 %}
                        1.000.000 - 1.500.000
                    {% elif offer.salary == 20 %}
                        1.500.000 - 2.000.000
                    {% elif offer.salary == 25 %}
                        2.000.000 - 2.500.000
                    {% elif offer.salary == 30 %}
                        2.500.000 - 3.000.000
                    {% elif offer.salary == 35 %}
                        3.000.000 - 3.500.000
                    {% elif offer.salary == 40 %}
                        3.500.000 - 4.000.000
                    {% elif offer.salary == 45 %}
                        4.000.000 - 4.500.000
                    {% elif offer.salary == 50 %}
                        4.500.000 - 5.000.000
                    {% elif offer.salary == 55 %}
                        5.000.000 - More
                    {% endif %}
                </p>
            </div>
        </div>
       <div class="row-fluid">
            <div class="span6">
                <p>
                    <strong>Location:</strong> {{ offer.location }}
                </p>
            </div>
            <div class="span6">
                <p class="pull-right">
                    <strong>Time offer:</strong> {{ offer.offer_valid_time }}
                </p>
            </div>
        </div>
        
        <p align="justify">
            <strong>Description:</strong> {{ offer.job_description }} 
        </p>
        <p align="justify">
            <strong>Skills: </strong> 
            {% for tag in offer.skills.all %}
                <span class="label label-info">{{tag.name}}</span>
            {% endfor %}
            
        </p>
     </br>  
     <a class="btn btn-primary pull-right" href="#window" role="button" data-toggle="modal">Apply</a>
     <div id="window" class="modal hide fade">
         <div class="modal-header">
             <button type="button" class="close" data-dismiss="modal" area-hidden="true">X</button>
             <h3>Apply to {{offer.job_title}}</h3>
         </div>
         <div class="modal-body">
            <form action= "" method= "POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{form.as_p}}
                <input type= "submit" value= "Apply" class="btn btn-primary">
                <input type= "reset" value= "Clean" class="btn">
            </form>
         </div>
         <div class="modal-footer">
             <a href="#" class="btn" data-dismiss="modal">Cancel</a>
         </div>
     </div>
    </div>
{% endblock  %}

empleo_desarrolladores/templates/positions.html
{% extends 'base.html' %}
{% block content %}
	<div class="row-fluid">
		<a href="{% url 'create_position_view' %}" class="btn btn-primary pull-right">Create</a>
		<a href="{% url 'old_positions_list_view' %}" class="btn pull-right">Old</a>
	</div>
	<br>
	<br>
	{% for offer in offers %}
		{% ifnotequal offer.state 1 %}
			<div class="row-fluid bordered1">
				
					<div class="span9">
						<a href="/positions/details/{{offer.id}}"><h4>{{offer.job_title| upper}}</h4></a>
					</div>	
					
					<div class="span1">
						<span class="pull-right"><i class="icon-user"></i>{{offer.applicants.count}}</span>
					</div>

					<div class="span1">
					{% ifequal offer.state 0 %}
						<span class="label label-warning pull-right" style="margin-top:10px;">Draft</span>
					{% else %}
						<span class="label label-success pull-right" style="margin-top:10px;">Live</span>
					{% endifequal %}	
					</div>					
					<div class="span1">
						<span style="margin-top:10px;" ><a href="/positions/terminate/{{offer.id}}">Terminate</a> </span>
					</div>
				
			</div>
		{% endifnotequal %}
	{% empty %}
		<div class="bordered">
			<p align="center">
				<h3>Create an Offer!</h3>
			</p>
		</div>
	{% endfor %}
	
{% endblock %}